TARGET		:= nKaruga
TITLE		:= NKARUGA01
SOURCES		:= src
			
INCLUDES	:= include

PKG_CONFIG = arm-vita-eabi-pkg-config
SDL_CFLAGS := $(shell $(PKG_CONFIG) --cflags SDL2_mixer)
SDL_LIBS := $(shell $(PKG_CONFIG) --static --libs SDL2_mixer)

LIBS = -lvita2d $(SDL_LIBS) -lSceShaccCgExt -ltaihen_stub -ljpeg -lfreetype -lpng16 -lz \
	-lScePgf_stub

CFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))
OBJS     := $(CFILES:.c=.o) $(CPPFILES:.cpp=.o) 

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -fno-lto -g -Wl,-q -O3 $(SDL_CFLAGS) -DVITA
CXXFLAGS  = $(CFLAGS) -fno-exceptions -std=gnu++11 -fpermissive
ASFLAGS = $(CFLAGS)
# vita-elf-create appends import metadata to the executable segment.
LDFLAGS += -Wl,--defsym=__sce_headroom=0x10000

all: $(TARGET).vpk

$(TARGET).vpk: $(TARGET).velf
	vita-make-fself -c -s $< build/eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE) "$(TARGET)" build/sce_sys/param.sfo
	vita-pack-vpk -s build/sce_sys/param.sfo -b build/eboot.bin \
		--add build/sce_sys/icon0.png=sce_sys/icon0.png \
		--add build/sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
		--add build/sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
		--add build/sfx=sfx \
		--add build/nKaruga.cfg=nKaruga.cfg \
		--add build/sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
		$(TARGET).vpk
	
%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@

$(TARGET).elf: $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ $(LIBS) -o $@

clean:
	@rm -rf $(TARGET).velf $(TARGET).elf $(TARGET).elf.unstripped.elf $(OBJS) build/eboot.bin build/sce_sys/param.sfo
